version: "3.9"

services:
  php-app:
    build:
      context: .
      dockerfile: dockerfile
    volumes:
      - ./php:/var/www/html
    depends_on:
      - database-container
    ports:
      - 3000:80
  
  database-container:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: testUser
      MYSQL_DATABASE: budgetmanager
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin:latest
    links:
      - database-container
    ports:
      - "3001:80"
    environment:
      PMA_HOST: database-container
      MYSQL_ROOT_PASSWORD: ""