version: "3.8"

services:
  nginx:
    image: nginx:latest
    volumes:
      - ./www:/usr/share/nginx/html
      - ./default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "3000:80"
    networks:
      - internal
  
  php: 
    build: 
      context: .
      dockerfile: docker/php/dockerfile
    volumes:
      - ./www:/usr/share/nginx/html
    networks:
      - internal
  
  database-container:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: testUser
      MYSQL_DATABASE: budgetmanager
      MYSQL_PASSWORD: root
    networks:
      - internal

  phpmyadmin:
    image: phpmyadmin:latest
    ports:
      - "3001:80"
    environment:
      PMA_HOST: database-container
    networks:
      - internal

networks:
  internal:
    driver: bridge
  